dw_Tooltip.content_vars = {
	L1: 'Want to turn off your site while performing updates or other types of maintenance? <b>Please Note</b>: Administrators will still be able to see the site.',
	L2: 'Disable guest downloads.',
	L3: 'Allow Registrations via Invite System.',
	L4: 'How many invites should each user be given upon registration?',
	L5: 'Delete invite code after X days who didnt respond the invite request',
	L6: 'Allow Registrations (not need invite code)',
	L7: 'EMAIL: Sent confirmation email. ADMIN: Manual activate. AUTOMATIC: Activate user after registration.',
	L8: 'Enable or Disable wait system (see faq.php#46)',
	L9: 'Enable or Disable Maximum concurrent downloads (AKA Max Slots) (see faq.php#66)',
	L10: 'Show POLL system on main page.',
	L11: 'Show STATS system on main page.',
	L12: 'Show Last x Forum Posts on main page.',
	L13: 'Show Last x Torrents on main page.',
	L14: 'Show Server Load on main page.',
	L15: 'Show Whats Goin On Box on main page.',
	L16: 'Show Whats Goin On Box on forums page.',
	L17: 'Show shoutbox on main page.',
	L18: 'Show an legend with user-classes under the shoutbox.',
	L19: 'Default 1000000 (10 gb)',
	L20: 'Default 60 * 30 (1800) ',
	L21: 'Default 900 ',
	L22: 'Default  86400 * 3 (259200)',
	L23: 'Default 50000',
	L24: 'Default 1',
	L25: 'Default  6 * 3600 (21600)',
	L26: 'Disable registration whenever this limit will be reached.',
	L27: 'Website Email address',
	L28: 'Report Email address',
	L29: 'Website Name.',
	L30: 'Default fts-contents/torrents <b><u>NO</u> a trailing slash (/) at the end!</b>',
	L31: 'Default pic/ <b><u>ADD</u> a trailing slash (/) at the end!</b>',
	L32: 'Default categories <b><u>NO</u> a trailing slash (/) at the end!',
	L33: 'Default fts-contents/bitbucket <b><u>NO</u> a trailing slash (/) at the end!</b>',
	L34: 'Default fts-contents/cache <b><u>NO</u> a trailing slash (/) at the end!</b>',
	L35: 'Please enter your mysql host name.',
	L36: 'Please enter your mysql user name.',
	L37: 'Please enter your mysql password.',
	L38: 'Please enter database name of your tracker.',
	L39: 'Example: Last seen(Location)	Browsing Torrent Lists...',
	L40: 'Log IP address which user have a different IP. (userlogin() function)',
	L41: 'Log ALL IP address into database if not exists. (iplogger() function)',
	L42: 'Check ever1 URL on your tracker for hacking attempt!',
	L43: 'Enable KPS or Disable but keep points KPS or Disable KPS',
	L44: 'Refresh page at a given interval (in seconds)',
	L45: 'Enable/Disable Left Menu function.',
	L46: 'This splits your torrent by day in browse.',
	L47: 'The nickname(username) of the Bot.',
     L48: 'ShoutBot can do only those listed below actions.<BR><b>Announce Torrents</b>(if you want this to be enabled write \'torrents\' separated by commas to the other duties.)<BR><b>Announce Cleanups</b>(if you want this to be enabled write \'cleanups\' separated by commas to the other duties)<BR><b>Announce Requests</b>(if you want this to be enabled write \'requests\' separated by commas to the other duties)<BR><b>Announce New Users</b>(if you want this to be enabled write \'users\' separated by commas to the other duties)<BR><b>Announce New Topics</b>(if you want this to be enabled write \'topcics\' separated by commas to the other duties)<BR>EG: To use all the duties write \'torrents,cleanups,requests,users,topics\'',  
	L49: 'With this enable people can upload an movie within few minutes.',
	L50: 'This will show a little bar on browse and details showing torrent\'s progress.',
	L51: 'This will make a new topic in forum each time a poll is made.',
	L52: 'This will show an Search Cloud in browse page.',
	L53: 'Login with a secure method',
	L54: 'Modify torrents to be private.',
	L55: 'Require users to enter a Visual Verify Code to register/login/recover?',
	L56: 'Use it to stop surfers from easily saving your web page, viewing its source, or lifting images off your site when using either IE 4+ or NS 4+.',
	L57: 'This will stop keyloggers from stealing account passwords.',
	L58: 'Disable registration with same IP Address.',
	L59: 'Disable/Ban IP address who exceed this limit.',
	L60: 'How the news should be displayed?',
	L61: 'Enable Referral System?',
	L62: 'Users will be able to post an youtube link to upload page',
	img_txt1: {
        txt: 'Cranes mandala',
        w: 160,
    }
}